cogip_django/urls.py
from django.contrib import admin
from django.urls import path, include

from office.views import home, signup

urlpatterns = [
    path('', home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('my-office-admin/',  admin.site.urls),
    path('office/', include('office.urls')),
    path('user-signup', signup, name="signup")
]
admin.site.urls

office/urls.py
from django.urls import path, reverse_lazy

from office.models import Company, Contact, Invoice
from office.views import HomeView, OfficeUpdateView, OfficeDeleteView, OfficeCreateView, \
    contact_details, company_details, invoice_details

app_name = "office"


urlpatterns = [
    path('company/', HomeView.as_view(model=Company, template_name='office/company/company_home.html', context_object_name='companies'), name='company-home'),
    path('contact/', HomeView.as_view(model=Contact, template_name='office/contact/contact_home.html', context_object_name='contacts'), name='contact-home'),
    path('invoice/', HomeView.as_view(model=Invoice, template_name='office/invoice/invoice_home.html', context_object_name='invoices'), name='invoice-home'),
    path('company/<str:slug>/', company_details, name='company-detail'),
    path('contact/<str:slug>/', contact_details, name='contact-detail'),
    path('invoice/<str:pk>/', invoice_details, name='invoice-detail'),
    path('company-create/',
         OfficeCreateView.as_view(model=Company, template_name='office/company/company_create.html', fields=['name', 'vat_number', 'type', 'country']),
         name='company-create'),
    path('contact-create/',
         OfficeCreateView.as_view(model=Contact, template_name='office/contact/contact_create.html', fields=['firstname', 'lastname', 'phone', 'email', 'company']),
         name='contact-create'),
    path('invoice-create/',
         OfficeCreateView.as_view(model=Invoice, template_name='office/invoice/invoice_create.html', fields=['company', 'contact']),
         name='invoice-create'),
    path('company-edit/<str:slug>/',
         OfficeUpdateView.as_view(model=Company, template_name='office/company/company_edit.html', fields=['name', 'vat_number', 'type', 'country']),
         name='company-edit'),
    path('contact-edit/<str:slug>/',
         OfficeUpdateView.as_view(model=Contact, template_name='office/contact/contact_edit.html', fields=['firstname', 'lastname', 'phone', 'email', 'company']),
         name='contact-edit'),
    path('invoice-edit/<str:pk>/',
         OfficeUpdateView.as_view(model=Invoice, template_name='office/invoice/invoice_edit.html', fields=['company', 'contact']),
         name='invoice-edit'),
    path('company-delete/<str:slug>/',
         OfficeDeleteView.as_view(model=Company, template_name='office/company/company_confirm_delete.html', context_object_name='company', success_url=reverse_lazy('office:company-home')),
         name='company-delete'),
    path('contact-delete/<str:slug>/',
         OfficeDeleteView.as_view(model=Contact, template_name='office/contact/contact_confirm_delete.html', context_object_name='contact', success_url=reverse_lazy('office:contact-home')),
         name='contact-delete'),
    path('invoice-delete/<str:pk>/',
         OfficeDeleteView.as_view(model=Invoice, template_name='office/invoice/invoice_confirm_delete.html', context_object_name='invoice', success_url=reverse_lazy('office:invoice-home')),
         name='invoice-delete'),

]

office/models.py
from django.contrib.auth import apps
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

from office.countries import COUNTRIES

from datetime import datetime


class Company(models.Model):
    # Type of company choices
    CHOICES = (
        ('Prov', 'Provider'),
        ('Cli', 'Client')
    )
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120, unique=True, blank=True)
    vat_number = models.CharField(max_length=100, blank=True)
    type = models.CharField(max_length=100, choices=CHOICES, default='Prov')
    country = models.CharField(max_length=100, choices=COUNTRIES, blank=True)

    class Meta:
        verbose_name = "Compagnie"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    @property
    def type_value(self):
        return self.get_type_display()

    @property
    def country_value(self):
        return self.get_country_display()

    def get_absolute_url(self):
        return reverse('office:company-detail', kwargs={'slug': self.slug})


class Contact(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    email = models.EmailField()
    slug = models.SlugField(max_length=120, unique=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)


    class Meta:
        verbose_name = "Contact"

    @property
    def fullname(self):
        return f"{self.firstname} {self.lastname}"

    def __str__(self):
        return self.fullname

    def save(self, *args, **kwargs):
        self.slug = slugify(self.fullname)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('office:contact-detail', kwargs={'slug': self.slug})


class Invoice(models.Model):
    increment_num = 0
    number = models.CharField(max_length=100, unique=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)

    def __str__(self):
        return self.number

    def save(self, *args, **kwargs):
        today = datetime.now()
        year = today.year
        month = today.month
        day = today.day
        if not self.number:
            self.number = f"F{year}{month}{day}-{str(Invoice.increment_num).rjust(3, '0')}"
        Invoice.increment_num += 1
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('office:invoice-detail', kwargs={'pk': self.pk})


class CustomUserManager(BaseUserManager):
    def create_user(self, username, password):
        if not username:
            raise ValueError("Vous devez rentrer un nom d'utilisateur")
        user = self.model(username=username)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, password):
        user = self.create_user(username=username, password=password)
        user.is_staff = True
        user.is_admin = True
        user.save()
        return user


class CustomUser(AbstractBaseUser):
    username = models.CharField(max_length=100, unique=True, blank=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = "username"
    objects = CustomUserManager()

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

office/forms.py
from django.contrib.auth.forms import UserCreationForm

from office.models import CustomUser


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username",)

office/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from office.forms import UserRegistrationForm
from office.models import Company, Contact, Invoice
from django.views import View


def home(request):
    companies = Company.objects.all().order_by('-pk')[:5]
    contacts = Contact.objects.all().order_by('-pk')[:5]
    invoices = Invoice.objects.all().order_by('-date')[:5]
    context = {
        'companies': companies,
        'contacts': contacts,
        'invoices': invoices,
    }
    return render(request, 'office/home.html', context=context)


def company_details(request, slug):
    company = Company.objects.get(slug=slug)
    contacts = Contact.objects.filter(company_id=company.id)
    invoices = Invoice.objects.filter(company_id=company.id)
    context = {
        'company': company,
        'contacts': contacts,
        'invoices': invoices
    }
    return render(request, 'office/company/company_detail.html', context=context)


def contact_details(request, slug):
    contact = Contact.objects.get(slug=slug)
    invoices = Invoice.objects.filter(contact_id=contact.id)
    context = {
        'contact': contact,
        'invoices': invoices,
    }
    return render(request, 'office/contact/contact_detail.html', context=context)


def invoice_details(request, pk):
    invoice = Invoice.objects.get(pk=pk)
    contact = Contact.objects.get(pk=invoice.contact_id)
    company = Company.objects.get(pk=invoice.company_id)
    context = {
        'company': company,
        'contact': contact,
        'invoice': invoice
    }
    return render(request, 'office/invoice/invoice_detail.html', context=context)


class HomeView(ListView):
    model = 'default'
    template_name = 'office/home.html'
    context_object_name = 'default'


@method_decorator(login_required, name='dispatch')
class OfficeCreateView(CreateView):
    model = 'default'
    template_name = 'office/home.html'
    fields = []


class UserIsAdminMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_admin

    def handle_no_permission(self):
        return redirect('home')


@method_decorator(login_required, name='dispatch')
class OfficeUpdateView(UserIsAdminMixin, UpdateView):
    model = 'default'
    template_name = 'office/home.html'
    fields = []


@method_decorator(login_required, name='dispatch')
class OfficeDeleteView(UserIsAdminMixin, DeleteView):
    model = "default"
    template_name = 'default'
    context_object_name = "default"
    success_url = reverse_lazy("home")


def signup(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home")
    else:
        form = UserRegistrationForm()

    return render(request, "users/signup.html", {"form": form})

office/templates/office/company/company_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Supprimer une companie</title>
{% endblock %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <p>Êtes-vous sûr de vouloir supprimer la compagnie "{{ company }}"?</p>
        <input type="submit" value="Oui, supprimer" class="btn btn-delete">
    </form>
    <a href="{% url 'office:company-detail' slug=company.slug %}"><button type="text">Retour</button></a>

{% endblock %}

office/templates/office/company/company_create.html
{% extends 'base.html' %}

    {% block title %}
        <title>Ajouter une companie</title>
    {% endblock %}

    {% block content %}
        <h1>Ajouter une companie</h1>

        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Créer" class="btn btn-submit">
        </form>
    {% endblock %}

office/templates/office/company/company_detail.html
{% extends 'base.html' %}

    {% block title %}
        <title>{{company.name}}</title>
    {% endblock %}

    {% block content %}
        <h1>Société : {{company.name}}</h1>

        {% if request.user.is_admin %}
            <ul>
                <li><a href="{% url 'office:company-edit' slug=company.slug %}">| edit</a></li>
                <li><a href="{% url 'office:company-delete' slug=company.slug %}">| supprimer</a></li>
            </ul>
        {% endif %}

        <table>
            <tr>
                <td>N° TVA :</td><td> {{ company.vat_number }} </td>
            </tr>
            <tr>
                <td>Pays :</td><td> {{ company.country_value }} </td>
            </tr>
            <tr>
                <td>Type :</td><td> {{ company.type_value }} </td>
            </tr>
        </table>
        <hr>
        <h2>Personnes de contact </h2>
        {% if contacts %}
            <table>
                <tr>
                    <th>Nom </th>
                    <th>Phone </th>
                    <th>Email </th>
                </tr>
                    {% for contact in contacts %}
                        <tr>
                            <td> {{ contact.fullname}} </td>
                            <td> {{ contact.phone}} </td>
                            <td> {{ contact.email}} </td>
                            <td><a href="{% url 'office:contact-detail' slug=contact.slug %}">| voir</a></td>
                        </tr>
                    {% endfor %}
            </table>
        {% else %}
            <a href="{% url 'office:contact-create' %}">+ nouveau contact</a>
        {% endif %}
        <hr>
        <h2>Factures :</h2>
        {% if invoices %}
            <table>
                <tr>
                    <th>N° facture </th>
                    <th>Date </th>
                    <th>Personne de contact </th>
                </tr>

                {% for invoice in invoices %}
                    <tr>
                        <td> {{ invoice.number}} </td>
                        <td> {{ invoice.date}} </td>
                        {% for contact in contacts %}
                            {% if invoice.contact_id == contact.id %}
                                <td> {{ contact.fullname }} </td>
                            {% endif %}
                        {% endfor %}
                        <td><a href="{% url 'office:invoice-detail' pk=invoice.id %}">| voir</a></td>
                    </tr>
                {% endfor %}
            </table>
        {% elif contacts %}
            <a href="{% url 'office:invoice-create' %}">+ nouvelle factures</a>
        {% else %}
            <p>Veuillez ajouter un nouveau contact pour la société {{company.name }} afin de créer une nouvelle facture</p>
        {% endif %}

    {% endblock %}

office/templates/office/company/company_edit.html
{% extends 'base.html' %}

    {% block title %}
        <title>Editer {{company.name}}</title>
    {% endblock %}

    {% block content %}
        <h1>Editer {{ company.name }}</h1>

        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Editer" class="btn btn-submit">
        </form>
    {% endblock %}

office/templates/office/company/company_home.html
{% extends 'base.html' %}

    {% block title %}
        <title>Company</title>
    {% endblock %}

    {% block content %}
        <h1> Company Home</h1>

        <h3>Clients</h3>
        <table>
            <tr>
                <th>Name </th>
                <th>VAT </th>
                <th>Country </th>
            </tr>
            {% for company in companies %}
                {% if company.type == 'Cli' %}
                    <tr>
                        <td> {{ company.name }}</td>
                        <td> {{ company.vat_num }}</td>
                        <td> {{ company.country_value }}</td>
                        <td><a href="{% url 'office:company-detail' slug=company.slug %}">voir</a></td>
                        {% if request.user.is_admin %}
                            <td><a href="{% url 'office:company-delete' slug=company.slug %}">| supprimer</a></td>
                        {% endif %}
                    </tr>
                {% endif %}
            {% endfor %}
        </table>

        <h3>Fournisseurs</h3>
        <table>
            <tr>
                <th>Name </th>
                <th>VAT </th>
                <th>Country </th>
            </tr>
            {% for company in companies %}
                {% if company.type == 'Prov' %}
                    <tr>
                        <td> {{ company.name }}</td>
                        <td> {{ company.vat_num }}</td>
                        <td> {{ company.country_value }}</td>
                        <td><a href="{% url 'office:company-detail' slug=company.slug %}">voir</a></td>
                        {% if request.user.is_admin %}
                            <td><a href="{% url 'office:company-delete' slug=company.slug %}">| supprimer</a></td>
                        {% endif %}
                        </tr>
                {% endif %}
            {% endfor %}
        </table>
    {% endblock %}